// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebook.proto

// Protobuf Java Version: 4.26.1
package br.com.danielschiavo.livrariavirtual.protos;

public interface EbookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Ebook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string nome = 2;</code>
   * @return Whether the nome field is set.
   */
  boolean hasNome();
  /**
   * <code>optional string nome = 2;</code>
   * @return The nome.
   */
  java.lang.String getNome();
  /**
   * <code>optional string nome = 2;</code>
   * @return The bytes for nome.
   */
  com.google.protobuf.ByteString
      getNomeBytes();

  /**
   * <code>optional string nome_arquivo = 3;</code>
   * @return Whether the nomeArquivo field is set.
   */
  boolean hasNomeArquivo();
  /**
   * <code>optional string nome_arquivo = 3;</code>
   * @return The nomeArquivo.
   */
  java.lang.String getNomeArquivo();
  /**
   * <code>optional string nome_arquivo = 3;</code>
   * @return The bytes for nomeArquivo.
   */
  com.google.protobuf.ByteString
      getNomeArquivoBytes();

  /**
   * <code>optional bytes imagem_capa = 4;</code>
   * @return Whether the imagemCapa field is set.
   */
  boolean hasImagemCapa();
  /**
   * <code>optional bytes imagem_capa = 4;</code>
   * @return The imagemCapa.
   */
  com.google.protobuf.ByteString getImagemCapa();

  /**
   * <code>optional int32 pagina_atual = 5;</code>
   * @return Whether the paginaAtual field is set.
   */
  boolean hasPaginaAtual();
  /**
   * <code>optional int32 pagina_atual = 5;</code>
   * @return The paginaAtual.
   */
  int getPaginaAtual();

  /**
   * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
   * @return Whether the dataEHoraAdicao field is set.
   */
  boolean hasDataEHoraAdicao();
  /**
   * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
   * @return The dataEHoraAdicao.
   */
  com.google.protobuf.Timestamp getDataEHoraAdicao();
  /**
   * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDataEHoraAdicaoOrBuilder();

  /**
   * <code>optional string senha_do_ebook = 7;</code>
   * @return Whether the senhaDoEbook field is set.
   */
  boolean hasSenhaDoEbook();
  /**
   * <code>optional string senha_do_ebook = 7;</code>
   * @return The senhaDoEbook.
   */
  java.lang.String getSenhaDoEbook();
  /**
   * <code>optional string senha_do_ebook = 7;</code>
   * @return The bytes for senhaDoEbook.
   */
  com.google.protobuf.ByteString
      getSenhaDoEbookBytes();
}
