// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ebook.proto

// Protobuf Java Version: 4.26.1
package br.com.danielschiavo.livrariavirtual.protos;

/**
 * Protobuf type {@code Ebook}
 */
public final class Ebook extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Ebook)
    EbookOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Ebook.class.getName());
  }
  // Use Ebook.newBuilder() to construct.
  private Ebook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Ebook() {
    id_ = "";
    nome_ = "";
    nomeArquivo_ = "";
    imagemCapa_ = com.google.protobuf.ByteString.EMPTY;
    senhaDoEbook_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.danielschiavo.livrariavirtual.protos.EbookProto.internal_static_Ebook_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.danielschiavo.livrariavirtual.protos.EbookProto.internal_static_Ebook_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.danielschiavo.livrariavirtual.protos.Ebook.class, br.com.danielschiavo.livrariavirtual.protos.Ebook.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>optional string id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>optional string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nome_ = "";
  /**
   * <code>optional string nome = 2;</code>
   * @return Whether the nome field is set.
   */
  @java.lang.Override
  public boolean hasNome() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string nome = 2;</code>
   * @return The nome.
   */
  @java.lang.Override
  public java.lang.String getNome() {
    java.lang.Object ref = nome_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nome_ = s;
      return s;
    }
  }
  /**
   * <code>optional string nome = 2;</code>
   * @return The bytes for nome.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNomeBytes() {
    java.lang.Object ref = nome_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nome_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOME_ARQUIVO_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nomeArquivo_ = "";
  /**
   * <code>optional string nome_arquivo = 3;</code>
   * @return Whether the nomeArquivo field is set.
   */
  @java.lang.Override
  public boolean hasNomeArquivo() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string nome_arquivo = 3;</code>
   * @return The nomeArquivo.
   */
  @java.lang.Override
  public java.lang.String getNomeArquivo() {
    java.lang.Object ref = nomeArquivo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nomeArquivo_ = s;
      return s;
    }
  }
  /**
   * <code>optional string nome_arquivo = 3;</code>
   * @return The bytes for nomeArquivo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNomeArquivoBytes() {
    java.lang.Object ref = nomeArquivo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nomeArquivo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGEM_CAPA_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString imagemCapa_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>optional bytes imagem_capa = 4;</code>
   * @return Whether the imagemCapa field is set.
   */
  @java.lang.Override
  public boolean hasImagemCapa() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional bytes imagem_capa = 4;</code>
   * @return The imagemCapa.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getImagemCapa() {
    return imagemCapa_;
  }

  public static final int PAGINA_ATUAL_FIELD_NUMBER = 5;
  private int paginaAtual_ = 0;
  /**
   * <code>optional int32 pagina_atual = 5;</code>
   * @return Whether the paginaAtual field is set.
   */
  @java.lang.Override
  public boolean hasPaginaAtual() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 pagina_atual = 5;</code>
   * @return The paginaAtual.
   */
  @java.lang.Override
  public int getPaginaAtual() {
    return paginaAtual_;
  }

  public static final int DATA_E_HORA_ADICAO_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp dataEHoraAdicao_;
  /**
   * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
   * @return Whether the dataEHoraAdicao field is set.
   */
  @java.lang.Override
  public boolean hasDataEHoraAdicao() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
   * @return The dataEHoraAdicao.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDataEHoraAdicao() {
    return dataEHoraAdicao_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dataEHoraAdicao_;
  }
  /**
   * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDataEHoraAdicaoOrBuilder() {
    return dataEHoraAdicao_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dataEHoraAdicao_;
  }

  public static final int SENHA_DO_EBOOK_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object senhaDoEbook_ = "";
  /**
   * <code>optional string senha_do_ebook = 7;</code>
   * @return Whether the senhaDoEbook field is set.
   */
  @java.lang.Override
  public boolean hasSenhaDoEbook() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>optional string senha_do_ebook = 7;</code>
   * @return The senhaDoEbook.
   */
  @java.lang.Override
  public java.lang.String getSenhaDoEbook() {
    java.lang.Object ref = senhaDoEbook_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senhaDoEbook_ = s;
      return s;
    }
  }
  /**
   * <code>optional string senha_do_ebook = 7;</code>
   * @return The bytes for senhaDoEbook.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenhaDoEbookBytes() {
    java.lang.Object ref = senhaDoEbook_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senhaDoEbook_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, nome_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, nomeArquivo_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeBytes(4, imagemCapa_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(5, paginaAtual_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(6, getDataEHoraAdicao());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, senhaDoEbook_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, nome_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, nomeArquivo_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, imagemCapa_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, paginaAtual_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getDataEHoraAdicao());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, senhaDoEbook_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.danielschiavo.livrariavirtual.protos.Ebook)) {
      return super.equals(obj);
    }
    br.com.danielschiavo.livrariavirtual.protos.Ebook other = (br.com.danielschiavo.livrariavirtual.protos.Ebook) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasNome() != other.hasNome()) return false;
    if (hasNome()) {
      if (!getNome()
          .equals(other.getNome())) return false;
    }
    if (hasNomeArquivo() != other.hasNomeArquivo()) return false;
    if (hasNomeArquivo()) {
      if (!getNomeArquivo()
          .equals(other.getNomeArquivo())) return false;
    }
    if (hasImagemCapa() != other.hasImagemCapa()) return false;
    if (hasImagemCapa()) {
      if (!getImagemCapa()
          .equals(other.getImagemCapa())) return false;
    }
    if (hasPaginaAtual() != other.hasPaginaAtual()) return false;
    if (hasPaginaAtual()) {
      if (getPaginaAtual()
          != other.getPaginaAtual()) return false;
    }
    if (hasDataEHoraAdicao() != other.hasDataEHoraAdicao()) return false;
    if (hasDataEHoraAdicao()) {
      if (!getDataEHoraAdicao()
          .equals(other.getDataEHoraAdicao())) return false;
    }
    if (hasSenhaDoEbook() != other.hasSenhaDoEbook()) return false;
    if (hasSenhaDoEbook()) {
      if (!getSenhaDoEbook()
          .equals(other.getSenhaDoEbook())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasNome()) {
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
    }
    if (hasNomeArquivo()) {
      hash = (37 * hash) + NOME_ARQUIVO_FIELD_NUMBER;
      hash = (53 * hash) + getNomeArquivo().hashCode();
    }
    if (hasImagemCapa()) {
      hash = (37 * hash) + IMAGEM_CAPA_FIELD_NUMBER;
      hash = (53 * hash) + getImagemCapa().hashCode();
    }
    if (hasPaginaAtual()) {
      hash = (37 * hash) + PAGINA_ATUAL_FIELD_NUMBER;
      hash = (53 * hash) + getPaginaAtual();
    }
    if (hasDataEHoraAdicao()) {
      hash = (37 * hash) + DATA_E_HORA_ADICAO_FIELD_NUMBER;
      hash = (53 * hash) + getDataEHoraAdicao().hashCode();
    }
    if (hasSenhaDoEbook()) {
      hash = (37 * hash) + SENHA_DO_EBOOK_FIELD_NUMBER;
      hash = (53 * hash) + getSenhaDoEbook().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.danielschiavo.livrariavirtual.protos.Ebook parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Ebook parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Ebook parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Ebook parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Ebook parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Ebook parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Ebook parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Ebook parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static br.com.danielschiavo.livrariavirtual.protos.Ebook parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static br.com.danielschiavo.livrariavirtual.protos.Ebook parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Ebook parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Ebook parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.danielschiavo.livrariavirtual.protos.Ebook prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Ebook}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Ebook)
      br.com.danielschiavo.livrariavirtual.protos.EbookOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.danielschiavo.livrariavirtual.protos.EbookProto.internal_static_Ebook_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.danielschiavo.livrariavirtual.protos.EbookProto.internal_static_Ebook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.danielschiavo.livrariavirtual.protos.Ebook.class, br.com.danielschiavo.livrariavirtual.protos.Ebook.Builder.class);
    }

    // Construct using br.com.danielschiavo.livrariavirtual.protos.Ebook.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getDataEHoraAdicaoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      nome_ = "";
      nomeArquivo_ = "";
      imagemCapa_ = com.google.protobuf.ByteString.EMPTY;
      paginaAtual_ = 0;
      dataEHoraAdicao_ = null;
      if (dataEHoraAdicaoBuilder_ != null) {
        dataEHoraAdicaoBuilder_.dispose();
        dataEHoraAdicaoBuilder_ = null;
      }
      senhaDoEbook_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.danielschiavo.livrariavirtual.protos.EbookProto.internal_static_Ebook_descriptor;
    }

    @java.lang.Override
    public br.com.danielschiavo.livrariavirtual.protos.Ebook getDefaultInstanceForType() {
      return br.com.danielschiavo.livrariavirtual.protos.Ebook.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.danielschiavo.livrariavirtual.protos.Ebook build() {
      br.com.danielschiavo.livrariavirtual.protos.Ebook result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.danielschiavo.livrariavirtual.protos.Ebook buildPartial() {
      br.com.danielschiavo.livrariavirtual.protos.Ebook result = new br.com.danielschiavo.livrariavirtual.protos.Ebook(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(br.com.danielschiavo.livrariavirtual.protos.Ebook result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nome_ = nome_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.nomeArquivo_ = nomeArquivo_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.imagemCapa_ = imagemCapa_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.paginaAtual_ = paginaAtual_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.dataEHoraAdicao_ = dataEHoraAdicaoBuilder_ == null
            ? dataEHoraAdicao_
            : dataEHoraAdicaoBuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.senhaDoEbook_ = senhaDoEbook_;
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.danielschiavo.livrariavirtual.protos.Ebook) {
        return mergeFrom((br.com.danielschiavo.livrariavirtual.protos.Ebook)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.danielschiavo.livrariavirtual.protos.Ebook other) {
      if (other == br.com.danielschiavo.livrariavirtual.protos.Ebook.getDefaultInstance()) return this;
      if (other.hasId()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasNome()) {
        nome_ = other.nome_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasNomeArquivo()) {
        nomeArquivo_ = other.nomeArquivo_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasImagemCapa()) {
        setImagemCapa(other.getImagemCapa());
      }
      if (other.hasPaginaAtual()) {
        setPaginaAtual(other.getPaginaAtual());
      }
      if (other.hasDataEHoraAdicao()) {
        mergeDataEHoraAdicao(other.getDataEHoraAdicao());
      }
      if (other.hasSenhaDoEbook()) {
        senhaDoEbook_ = other.senhaDoEbook_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              nome_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              nomeArquivo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              imagemCapa_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              paginaAtual_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              input.readMessage(
                  getDataEHoraAdicaoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              senhaDoEbook_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>optional string id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object nome_ = "";
    /**
     * <code>optional string nome = 2;</code>
     * @return Whether the nome field is set.
     */
    public boolean hasNome() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string nome = 2;</code>
     * @return The nome.
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string nome = 2;</code>
     * @return The bytes for nome.
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nome = 2;</code>
     * @param value The nome to set.
     * @return This builder for chaining.
     */
    public Builder setNome(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nome_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nome = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNome() {
      nome_ = getDefaultInstance().getNome();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string nome = 2;</code>
     * @param value The bytes for nome to set.
     * @return This builder for chaining.
     */
    public Builder setNomeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nome_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object nomeArquivo_ = "";
    /**
     * <code>optional string nome_arquivo = 3;</code>
     * @return Whether the nomeArquivo field is set.
     */
    public boolean hasNomeArquivo() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string nome_arquivo = 3;</code>
     * @return The nomeArquivo.
     */
    public java.lang.String getNomeArquivo() {
      java.lang.Object ref = nomeArquivo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nomeArquivo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string nome_arquivo = 3;</code>
     * @return The bytes for nomeArquivo.
     */
    public com.google.protobuf.ByteString
        getNomeArquivoBytes() {
      java.lang.Object ref = nomeArquivo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nomeArquivo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nome_arquivo = 3;</code>
     * @param value The nomeArquivo to set.
     * @return This builder for chaining.
     */
    public Builder setNomeArquivo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nomeArquivo_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nome_arquivo = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNomeArquivo() {
      nomeArquivo_ = getDefaultInstance().getNomeArquivo();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string nome_arquivo = 3;</code>
     * @param value The bytes for nomeArquivo to set.
     * @return This builder for chaining.
     */
    public Builder setNomeArquivoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nomeArquivo_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString imagemCapa_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes imagem_capa = 4;</code>
     * @return Whether the imagemCapa field is set.
     */
    @java.lang.Override
    public boolean hasImagemCapa() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes imagem_capa = 4;</code>
     * @return The imagemCapa.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getImagemCapa() {
      return imagemCapa_;
    }
    /**
     * <code>optional bytes imagem_capa = 4;</code>
     * @param value The imagemCapa to set.
     * @return This builder for chaining.
     */
    public Builder setImagemCapa(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      imagemCapa_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes imagem_capa = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearImagemCapa() {
      bitField0_ = (bitField0_ & ~0x00000008);
      imagemCapa_ = getDefaultInstance().getImagemCapa();
      onChanged();
      return this;
    }

    private int paginaAtual_ ;
    /**
     * <code>optional int32 pagina_atual = 5;</code>
     * @return Whether the paginaAtual field is set.
     */
    @java.lang.Override
    public boolean hasPaginaAtual() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 pagina_atual = 5;</code>
     * @return The paginaAtual.
     */
    @java.lang.Override
    public int getPaginaAtual() {
      return paginaAtual_;
    }
    /**
     * <code>optional int32 pagina_atual = 5;</code>
     * @param value The paginaAtual to set.
     * @return This builder for chaining.
     */
    public Builder setPaginaAtual(int value) {

      paginaAtual_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 pagina_atual = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaginaAtual() {
      bitField0_ = (bitField0_ & ~0x00000010);
      paginaAtual_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp dataEHoraAdicao_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dataEHoraAdicaoBuilder_;
    /**
     * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
     * @return Whether the dataEHoraAdicao field is set.
     */
    public boolean hasDataEHoraAdicao() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
     * @return The dataEHoraAdicao.
     */
    public com.google.protobuf.Timestamp getDataEHoraAdicao() {
      if (dataEHoraAdicaoBuilder_ == null) {
        return dataEHoraAdicao_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dataEHoraAdicao_;
      } else {
        return dataEHoraAdicaoBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
     */
    public Builder setDataEHoraAdicao(com.google.protobuf.Timestamp value) {
      if (dataEHoraAdicaoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataEHoraAdicao_ = value;
      } else {
        dataEHoraAdicaoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
     */
    public Builder setDataEHoraAdicao(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dataEHoraAdicaoBuilder_ == null) {
        dataEHoraAdicao_ = builderForValue.build();
      } else {
        dataEHoraAdicaoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
     */
    public Builder mergeDataEHoraAdicao(com.google.protobuf.Timestamp value) {
      if (dataEHoraAdicaoBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          dataEHoraAdicao_ != null &&
          dataEHoraAdicao_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getDataEHoraAdicaoBuilder().mergeFrom(value);
        } else {
          dataEHoraAdicao_ = value;
        }
      } else {
        dataEHoraAdicaoBuilder_.mergeFrom(value);
      }
      if (dataEHoraAdicao_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
     */
    public Builder clearDataEHoraAdicao() {
      bitField0_ = (bitField0_ & ~0x00000020);
      dataEHoraAdicao_ = null;
      if (dataEHoraAdicaoBuilder_ != null) {
        dataEHoraAdicaoBuilder_.dispose();
        dataEHoraAdicaoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDataEHoraAdicaoBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getDataEHoraAdicaoFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDataEHoraAdicaoOrBuilder() {
      if (dataEHoraAdicaoBuilder_ != null) {
        return dataEHoraAdicaoBuilder_.getMessageOrBuilder();
      } else {
        return dataEHoraAdicao_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dataEHoraAdicao_;
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp data_e_hora_adicao = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDataEHoraAdicaoFieldBuilder() {
      if (dataEHoraAdicaoBuilder_ == null) {
        dataEHoraAdicaoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDataEHoraAdicao(),
                getParentForChildren(),
                isClean());
        dataEHoraAdicao_ = null;
      }
      return dataEHoraAdicaoBuilder_;
    }

    private java.lang.Object senhaDoEbook_ = "";
    /**
     * <code>optional string senha_do_ebook = 7;</code>
     * @return Whether the senhaDoEbook field is set.
     */
    public boolean hasSenhaDoEbook() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string senha_do_ebook = 7;</code>
     * @return The senhaDoEbook.
     */
    public java.lang.String getSenhaDoEbook() {
      java.lang.Object ref = senhaDoEbook_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senhaDoEbook_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string senha_do_ebook = 7;</code>
     * @return The bytes for senhaDoEbook.
     */
    public com.google.protobuf.ByteString
        getSenhaDoEbookBytes() {
      java.lang.Object ref = senhaDoEbook_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senhaDoEbook_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string senha_do_ebook = 7;</code>
     * @param value The senhaDoEbook to set.
     * @return This builder for chaining.
     */
    public Builder setSenhaDoEbook(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      senhaDoEbook_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>optional string senha_do_ebook = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenhaDoEbook() {
      senhaDoEbook_ = getDefaultInstance().getSenhaDoEbook();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>optional string senha_do_ebook = 7;</code>
     * @param value The bytes for senhaDoEbook to set.
     * @return This builder for chaining.
     */
    public Builder setSenhaDoEbookBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      senhaDoEbook_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Ebook)
  }

  // @@protoc_insertion_point(class_scope:Ebook)
  private static final br.com.danielschiavo.livrariavirtual.protos.Ebook DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.danielschiavo.livrariavirtual.protos.Ebook();
  }

  public static br.com.danielschiavo.livrariavirtual.protos.Ebook getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Ebook>
      PARSER = new com.google.protobuf.AbstractParser<Ebook>() {
    @java.lang.Override
    public Ebook parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Ebook> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Ebook> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.danielschiavo.livrariavirtual.protos.Ebook getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

