// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto
// Protobuf Java Version: 4.26.1

package br.com.danielschiavo.livrariavirtual.protos;

public final class UsuarioProto {
  private UsuarioProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      UsuarioProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Usuario_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Usuario_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rusuario.proto\032\013ebook.proto\"s\n\007Usuario\022" +
      "\017\n\002id\030\001 \001(\tH\000\210\001\001\022\021\n\004nome\030\002 \001(\tH\001\210\001\001\022\022\n\005e" +
      "mail\030\003 \001(\tH\002\210\001\001\022\026\n\006ebooks\030\004 \003(\0132\006.EbookB" +
      "\005\n\003_idB\007\n\005_nomeB\010\n\006_emailB=\n+br.com.dani" +
      "elschiavo.livrariavirtual.protosB\014Usuari" +
      "oProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          br.com.danielschiavo.livrariavirtual.protos.EbookProto.getDescriptor(),
        });
    internal_static_Usuario_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Usuario_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Usuario_descriptor,
        new java.lang.String[] { "Id", "Nome", "Email", "Ebooks", });
    descriptor.resolveAllFeaturesImmutable();
    br.com.danielschiavo.livrariavirtual.protos.EbookProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
