// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto

// Protobuf Java Version: 4.26.1
package br.com.danielschiavo.livrariavirtual.protos;

/**
 * Protobuf type {@code Usuario}
 */
public final class Usuario extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Usuario)
    UsuarioOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Usuario.class.getName());
  }
  // Use Usuario.newBuilder() to construct.
  private Usuario(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Usuario() {
    id_ = "";
    nome_ = "";
    email_ = "";
    ebooks_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return br.com.danielschiavo.livrariavirtual.protos.UsuarioProto.internal_static_Usuario_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return br.com.danielschiavo.livrariavirtual.protos.UsuarioProto.internal_static_Usuario_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            br.com.danielschiavo.livrariavirtual.protos.Usuario.class, br.com.danielschiavo.livrariavirtual.protos.Usuario.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>optional string id = 1;</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>optional string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nome_ = "";
  /**
   * <code>optional string nome = 2;</code>
   * @return Whether the nome field is set.
   */
  @java.lang.Override
  public boolean hasNome() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string nome = 2;</code>
   * @return The nome.
   */
  @java.lang.Override
  public java.lang.String getNome() {
    java.lang.Object ref = nome_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nome_ = s;
      return s;
    }
  }
  /**
   * <code>optional string nome = 2;</code>
   * @return The bytes for nome.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNomeBytes() {
    java.lang.Object ref = nome_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nome_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object email_ = "";
  /**
   * <code>optional string email = 3;</code>
   * @return Whether the email field is set.
   */
  @java.lang.Override
  public boolean hasEmail() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string email = 3;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>optional string email = 3;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EBOOKS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<br.com.danielschiavo.livrariavirtual.protos.Ebook> ebooks_;
  /**
   * <code>repeated .Ebook ebooks = 4;</code>
   */
  @java.lang.Override
  public java.util.List<br.com.danielschiavo.livrariavirtual.protos.Ebook> getEbooksList() {
    return ebooks_;
  }
  /**
   * <code>repeated .Ebook ebooks = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends br.com.danielschiavo.livrariavirtual.protos.EbookOrBuilder> 
      getEbooksOrBuilderList() {
    return ebooks_;
  }
  /**
   * <code>repeated .Ebook ebooks = 4;</code>
   */
  @java.lang.Override
  public int getEbooksCount() {
    return ebooks_.size();
  }
  /**
   * <code>repeated .Ebook ebooks = 4;</code>
   */
  @java.lang.Override
  public br.com.danielschiavo.livrariavirtual.protos.Ebook getEbooks(int index) {
    return ebooks_.get(index);
  }
  /**
   * <code>repeated .Ebook ebooks = 4;</code>
   */
  @java.lang.Override
  public br.com.danielschiavo.livrariavirtual.protos.EbookOrBuilder getEbooksOrBuilder(
      int index) {
    return ebooks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, nome_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, email_);
    }
    for (int i = 0; i < ebooks_.size(); i++) {
      output.writeMessage(4, ebooks_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, nome_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, email_);
    }
    for (int i = 0; i < ebooks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, ebooks_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof br.com.danielschiavo.livrariavirtual.protos.Usuario)) {
      return super.equals(obj);
    }
    br.com.danielschiavo.livrariavirtual.protos.Usuario other = (br.com.danielschiavo.livrariavirtual.protos.Usuario) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasNome() != other.hasNome()) return false;
    if (hasNome()) {
      if (!getNome()
          .equals(other.getNome())) return false;
    }
    if (hasEmail() != other.hasEmail()) return false;
    if (hasEmail()) {
      if (!getEmail()
          .equals(other.getEmail())) return false;
    }
    if (!getEbooksList()
        .equals(other.getEbooksList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasNome()) {
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
    }
    if (hasEmail()) {
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
    }
    if (getEbooksCount() > 0) {
      hash = (37 * hash) + EBOOKS_FIELD_NUMBER;
      hash = (53 * hash) + getEbooksList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static br.com.danielschiavo.livrariavirtual.protos.Usuario parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Usuario parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Usuario parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Usuario parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Usuario parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Usuario parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Usuario parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Usuario parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static br.com.danielschiavo.livrariavirtual.protos.Usuario parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static br.com.danielschiavo.livrariavirtual.protos.Usuario parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Usuario parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static br.com.danielschiavo.livrariavirtual.protos.Usuario parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(br.com.danielschiavo.livrariavirtual.protos.Usuario prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Usuario}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Usuario)
      br.com.danielschiavo.livrariavirtual.protos.UsuarioOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.com.danielschiavo.livrariavirtual.protos.UsuarioProto.internal_static_Usuario_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.com.danielschiavo.livrariavirtual.protos.UsuarioProto.internal_static_Usuario_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.com.danielschiavo.livrariavirtual.protos.Usuario.class, br.com.danielschiavo.livrariavirtual.protos.Usuario.Builder.class);
    }

    // Construct using br.com.danielschiavo.livrariavirtual.protos.Usuario.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      nome_ = "";
      email_ = "";
      if (ebooksBuilder_ == null) {
        ebooks_ = java.util.Collections.emptyList();
      } else {
        ebooks_ = null;
        ebooksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return br.com.danielschiavo.livrariavirtual.protos.UsuarioProto.internal_static_Usuario_descriptor;
    }

    @java.lang.Override
    public br.com.danielschiavo.livrariavirtual.protos.Usuario getDefaultInstanceForType() {
      return br.com.danielschiavo.livrariavirtual.protos.Usuario.getDefaultInstance();
    }

    @java.lang.Override
    public br.com.danielschiavo.livrariavirtual.protos.Usuario build() {
      br.com.danielschiavo.livrariavirtual.protos.Usuario result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public br.com.danielschiavo.livrariavirtual.protos.Usuario buildPartial() {
      br.com.danielschiavo.livrariavirtual.protos.Usuario result = new br.com.danielschiavo.livrariavirtual.protos.Usuario(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(br.com.danielschiavo.livrariavirtual.protos.Usuario result) {
      if (ebooksBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          ebooks_ = java.util.Collections.unmodifiableList(ebooks_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.ebooks_ = ebooks_;
      } else {
        result.ebooks_ = ebooksBuilder_.build();
      }
    }

    private void buildPartial0(br.com.danielschiavo.livrariavirtual.protos.Usuario result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nome_ = nome_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.email_ = email_;
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof br.com.danielschiavo.livrariavirtual.protos.Usuario) {
        return mergeFrom((br.com.danielschiavo.livrariavirtual.protos.Usuario)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(br.com.danielschiavo.livrariavirtual.protos.Usuario other) {
      if (other == br.com.danielschiavo.livrariavirtual.protos.Usuario.getDefaultInstance()) return this;
      if (other.hasId()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasNome()) {
        nome_ = other.nome_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasEmail()) {
        email_ = other.email_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (ebooksBuilder_ == null) {
        if (!other.ebooks_.isEmpty()) {
          if (ebooks_.isEmpty()) {
            ebooks_ = other.ebooks_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureEbooksIsMutable();
            ebooks_.addAll(other.ebooks_);
          }
          onChanged();
        }
      } else {
        if (!other.ebooks_.isEmpty()) {
          if (ebooksBuilder_.isEmpty()) {
            ebooksBuilder_.dispose();
            ebooksBuilder_ = null;
            ebooks_ = other.ebooks_;
            bitField0_ = (bitField0_ & ~0x00000008);
            ebooksBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getEbooksFieldBuilder() : null;
          } else {
            ebooksBuilder_.addAllMessages(other.ebooks_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              nome_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              br.com.danielschiavo.livrariavirtual.protos.Ebook m =
                  input.readMessage(
                      br.com.danielschiavo.livrariavirtual.protos.Ebook.parser(),
                      extensionRegistry);
              if (ebooksBuilder_ == null) {
                ensureEbooksIsMutable();
                ebooks_.add(m);
              } else {
                ebooksBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>optional string id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object nome_ = "";
    /**
     * <code>optional string nome = 2;</code>
     * @return Whether the nome field is set.
     */
    public boolean hasNome() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string nome = 2;</code>
     * @return The nome.
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string nome = 2;</code>
     * @return The bytes for nome.
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string nome = 2;</code>
     * @param value The nome to set.
     * @return This builder for chaining.
     */
    public Builder setNome(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nome_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string nome = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNome() {
      nome_ = getDefaultInstance().getNome();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string nome = 2;</code>
     * @param value The bytes for nome to set.
     * @return This builder for chaining.
     */
    public Builder setNomeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nome_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>optional string email = 3;</code>
     * @return Whether the email field is set.
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string email = 3;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string email = 3;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string email = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = getDefaultInstance().getEmail();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string email = 3;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      email_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<br.com.danielschiavo.livrariavirtual.protos.Ebook> ebooks_ =
      java.util.Collections.emptyList();
    private void ensureEbooksIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        ebooks_ = new java.util.ArrayList<br.com.danielschiavo.livrariavirtual.protos.Ebook>(ebooks_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        br.com.danielschiavo.livrariavirtual.protos.Ebook, br.com.danielschiavo.livrariavirtual.protos.Ebook.Builder, br.com.danielschiavo.livrariavirtual.protos.EbookOrBuilder> ebooksBuilder_;

    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public java.util.List<br.com.danielschiavo.livrariavirtual.protos.Ebook> getEbooksList() {
      if (ebooksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ebooks_);
      } else {
        return ebooksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public int getEbooksCount() {
      if (ebooksBuilder_ == null) {
        return ebooks_.size();
      } else {
        return ebooksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public br.com.danielschiavo.livrariavirtual.protos.Ebook getEbooks(int index) {
      if (ebooksBuilder_ == null) {
        return ebooks_.get(index);
      } else {
        return ebooksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public Builder setEbooks(
        int index, br.com.danielschiavo.livrariavirtual.protos.Ebook value) {
      if (ebooksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEbooksIsMutable();
        ebooks_.set(index, value);
        onChanged();
      } else {
        ebooksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public Builder setEbooks(
        int index, br.com.danielschiavo.livrariavirtual.protos.Ebook.Builder builderForValue) {
      if (ebooksBuilder_ == null) {
        ensureEbooksIsMutable();
        ebooks_.set(index, builderForValue.build());
        onChanged();
      } else {
        ebooksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public Builder addEbooks(br.com.danielschiavo.livrariavirtual.protos.Ebook value) {
      if (ebooksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEbooksIsMutable();
        ebooks_.add(value);
        onChanged();
      } else {
        ebooksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public Builder addEbooks(
        int index, br.com.danielschiavo.livrariavirtual.protos.Ebook value) {
      if (ebooksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEbooksIsMutable();
        ebooks_.add(index, value);
        onChanged();
      } else {
        ebooksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public Builder addEbooks(
        br.com.danielschiavo.livrariavirtual.protos.Ebook.Builder builderForValue) {
      if (ebooksBuilder_ == null) {
        ensureEbooksIsMutable();
        ebooks_.add(builderForValue.build());
        onChanged();
      } else {
        ebooksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public Builder addEbooks(
        int index, br.com.danielschiavo.livrariavirtual.protos.Ebook.Builder builderForValue) {
      if (ebooksBuilder_ == null) {
        ensureEbooksIsMutable();
        ebooks_.add(index, builderForValue.build());
        onChanged();
      } else {
        ebooksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public Builder addAllEbooks(
        java.lang.Iterable<? extends br.com.danielschiavo.livrariavirtual.protos.Ebook> values) {
      if (ebooksBuilder_ == null) {
        ensureEbooksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ebooks_);
        onChanged();
      } else {
        ebooksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public Builder clearEbooks() {
      if (ebooksBuilder_ == null) {
        ebooks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        ebooksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public Builder removeEbooks(int index) {
      if (ebooksBuilder_ == null) {
        ensureEbooksIsMutable();
        ebooks_.remove(index);
        onChanged();
      } else {
        ebooksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public br.com.danielschiavo.livrariavirtual.protos.Ebook.Builder getEbooksBuilder(
        int index) {
      return getEbooksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public br.com.danielschiavo.livrariavirtual.protos.EbookOrBuilder getEbooksOrBuilder(
        int index) {
      if (ebooksBuilder_ == null) {
        return ebooks_.get(index);  } else {
        return ebooksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public java.util.List<? extends br.com.danielschiavo.livrariavirtual.protos.EbookOrBuilder> 
         getEbooksOrBuilderList() {
      if (ebooksBuilder_ != null) {
        return ebooksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ebooks_);
      }
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public br.com.danielschiavo.livrariavirtual.protos.Ebook.Builder addEbooksBuilder() {
      return getEbooksFieldBuilder().addBuilder(
          br.com.danielschiavo.livrariavirtual.protos.Ebook.getDefaultInstance());
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public br.com.danielschiavo.livrariavirtual.protos.Ebook.Builder addEbooksBuilder(
        int index) {
      return getEbooksFieldBuilder().addBuilder(
          index, br.com.danielschiavo.livrariavirtual.protos.Ebook.getDefaultInstance());
    }
    /**
     * <code>repeated .Ebook ebooks = 4;</code>
     */
    public java.util.List<br.com.danielschiavo.livrariavirtual.protos.Ebook.Builder> 
         getEbooksBuilderList() {
      return getEbooksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        br.com.danielschiavo.livrariavirtual.protos.Ebook, br.com.danielschiavo.livrariavirtual.protos.Ebook.Builder, br.com.danielschiavo.livrariavirtual.protos.EbookOrBuilder> 
        getEbooksFieldBuilder() {
      if (ebooksBuilder_ == null) {
        ebooksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            br.com.danielschiavo.livrariavirtual.protos.Ebook, br.com.danielschiavo.livrariavirtual.protos.Ebook.Builder, br.com.danielschiavo.livrariavirtual.protos.EbookOrBuilder>(
                ebooks_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        ebooks_ = null;
      }
      return ebooksBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Usuario)
  }

  // @@protoc_insertion_point(class_scope:Usuario)
  private static final br.com.danielschiavo.livrariavirtual.protos.Usuario DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new br.com.danielschiavo.livrariavirtual.protos.Usuario();
  }

  public static br.com.danielschiavo.livrariavirtual.protos.Usuario getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Usuario>
      PARSER = new com.google.protobuf.AbstractParser<Usuario>() {
    @java.lang.Override
    public Usuario parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Usuario> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Usuario> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public br.com.danielschiavo.livrariavirtual.protos.Usuario getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

