// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usuario.proto

// Protobuf Java Version: 4.26.1
package br.com.danielschiavo.livrariavirtual.protos;

public interface UsuarioOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Usuario)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>optional string nome = 2;</code>
   * @return Whether the nome field is set.
   */
  boolean hasNome();
  /**
   * <code>optional string nome = 2;</code>
   * @return The nome.
   */
  java.lang.String getNome();
  /**
   * <code>optional string nome = 2;</code>
   * @return The bytes for nome.
   */
  com.google.protobuf.ByteString
      getNomeBytes();

  /**
   * <code>optional string email = 3;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .Ebook ebooks = 4;</code>
   */
  java.util.List<br.com.danielschiavo.livrariavirtual.protos.Ebook> 
      getEbooksList();
  /**
   * <code>repeated .Ebook ebooks = 4;</code>
   */
  br.com.danielschiavo.livrariavirtual.protos.Ebook getEbooks(int index);
  /**
   * <code>repeated .Ebook ebooks = 4;</code>
   */
  int getEbooksCount();
  /**
   * <code>repeated .Ebook ebooks = 4;</code>
   */
  java.util.List<? extends br.com.danielschiavo.livrariavirtual.protos.EbookOrBuilder> 
      getEbooksOrBuilderList();
  /**
   * <code>repeated .Ebook ebooks = 4;</code>
   */
  br.com.danielschiavo.livrariavirtual.protos.EbookOrBuilder getEbooksOrBuilder(
      int index);
}
